steps:
  # Get the version from the git tag
  - name: "gcr.io/cloud-builders/git"
    args: ["describe", "--tags", "--abbrev=0", "--always"]
    id: GetVersion

  # Install dependencies
  - name: node:14.17.0
    entrypoint: yarn
    args: ["install"]
    dir: "/workspace"

  # Build the React app
  - name: node:14.17.0
    entrypoint: yarn
    args: ["build"]
    dir: "/workspace"

  # Build the Docker image with version tag
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "gcr.io/$PROJECT_ID/customer-projects-front-end:${_GIT_TAG}",
        ".",
      ]
    env:
      - "DOCKER_BUILDKIT=1"
      - "DOCKER_CLI_EXPERIMENTAL=enabled"
    substitutions:
      _GIT_TAG: "$$BUILD_ID" # Default to the build ID if tag not found
      # Uncomment the following to get the tag from GitHub releases
      # _GIT_TAG: "${REPO_NAME}-${TAG_NAME}-${_GIT_SHORT_SHA}"
      # REPO_NAME: "<your GitHub repo name>"
      # TAG_NAME: "$$REVISION_TAG_NAME"

    dir: "/workspace"

  # Push the Docker image to Google Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/customer-projects-front-end:${_GIT_TAG}"]

  # Deploy the Docker image to Cloud Run
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "run",
        "deploy",
        "customer-projects-front-end",
        "--image",
        "gcr.io/$PROJECT_ID/customer-projects-front-end:${_GIT_TAG}",
        "--platform",
        "managed",
        "--region",
        "us-central1",
        "--allow-unauthenticated",
      ]
    timeout: "1600s"
